DATETIME_FMT = "%Y-%m-%d %H:%M:%S"
MIN_BOOKING_MINUTES = 15
MAX_BOOKING_MINUTES = 480
GRACE_PERIOD_MINUTES = 10
QR_TOKEN_SALT = "booking-qr-v1"
VALID_PAYMENT_METHODS = {"upi", "card", "cash"}
BOOKING_STATUS_WAITING_TO_START = "waiting_to_start"
BOOKING_STATUS_CHARGING_STARTED = "charging_started"
BOOKING_STATUS_CHARGING_COMPLETED = "charging_completed"
BOOKING_STATUS_CANCELLED = "cancelled"
LEGACY_BOOKING_STATUS_CONFIRMED = "confirmed"
LEGACY_BOOKING_STATUS_COMPLETED = "completed"

DEFAULT_POWER_KW_BY_SLOT_TYPE = {
    "normal": 7.0,
    "fast": 50.0,
}

DEFAULT_PRICE_PER_KWH_BY_SLOT_TYPE = {
    "normal": 12.0,
    "fast": 18.0,
}
