services:
  - type: web
    name: evgo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --worker-class eventlet -w 1 app:app
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_DEBUG
        value: "0"
